name: Ping_plugin
version: 1.0-SNAPSHOT
main: me.shafi.ping_plugin.Ping_plugin
api-version: 1.15
authors: [shafi]
description: ment for /ping
commands:
    ping:
      description: do /ping to get your ping

